import argparse, json, os, pathlib, re, subprocess, time
root=pathlib.Path.cwd()
parser=argparse.ArgumentParser()
parser.add_argument('--binary', default=str(root/'target/release/weavepy'))
parser.add_argument('--out', type=pathlib.Path, default=root/'crates/weavepy-bench/census/2026-09-runtime-metadata/validation.json')
args=parser.parse_args()
output=args.out
output.parent.mkdir(parents=True, exist_ok=True)
os.environ['WEAVEPY_STDLIB_CACHE']=str(root/'target/performance-stdlib-cache')
results=[]
binary=str(pathlib.Path(args.binary).resolve())
def run(name, cmd, *, env=None, expected=None, timeout=180):
    start=time.monotonic()
    try:
        p=subprocess.run(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,env=env,timeout=timeout)
        passed=p.returncode==0 and (expected is None or p.stdout.replace('\r\n','\n')==expected)
        if name.startswith('cpython/'):
            passed = passed and bool(re.search(r'\| `cpython/Lib/test/[^`]+` \| pass \|', p.stdout))
        record=dict(name=name,passed=passed,returncode=p.returncode,seconds=time.monotonic()-start,stdout=p.stdout[-5000:],stderr=p.stderr[-5000:])
    except subprocess.TimeoutExpired:
        record=dict(name=name,passed=False,timeout=True,seconds=time.monotonic()-start)
    results.append(record)
    output.write_text(json.dumps(results,indent=2)+'\n')
    print(name,'PASS' if record['passed'] else 'FAIL',flush=True)
for name,flags,jit in [('jit',[],'1'),('interp',[],'0'),('gil0',['-X','gil=0'],'1')]:
    run('pickle_builtin_data_'+name,[binary,*flags,'tests/regrtest/test_pickle_builtin_data.py'],env={**os.environ,'WEAVEPY_JIT':jit},expected='pickle built-in data: ok\n')
    run('native_call_scratch_'+name,[binary,*flags,'tests/regrtest/test_native_call_scratch.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='native call scratch: ok\n')
    run('cached_code_relocation_'+name,[binary,*flags,'tests/regrtest/test_cached_code_relocation.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='cached code relocation: ok\n')
    run('sum_range_'+name,[binary,*flags,'tests/regrtest/test_sum_range.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('range_iteration_bounds_'+name,[binary,*flags,'tests/regrtest/test_range_iteration_bounds.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('sum_numeric_'+name,[binary,*flags,'tests/regrtest/test_sum_numeric.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('sum_streaming_'+name,[binary,*flags,'tests/regrtest/test_sum_streaming.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('range_collection_'+name,[binary,*flags,'tests/regrtest/test_range_collection.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('shared_code_caches_'+name,[binary,*flags,'tests/regrtest/test_shared_code_caches.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='shared code cache semantics: ok\n')
    run('lazy_instance_dict_'+name,[binary,*flags,'tests/regrtest/test_lazy_instance_dict.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='lazy instance dictionary semantics: ok\n')
    run('gc_metadata_'+name,[binary,*flags,'tests/regrtest/test_gc_metadata.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='collector metadata lifecycle: ok\n')
    run('string_split_gc_'+name,[binary,*flags,'tests/regrtest/test_string_split_gc.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('native_string_arguments_'+name,[binary,*flags,'tests/regrtest/test_native_string_arguments.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('native_string_callbacks_'+name,[binary,*flags,'tests/regrtest/test_native_string_callbacks.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('native_pin_pressure_'+name,[binary,*flags,'tests/regrtest/test_native_pin_pressure.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('native_generator_pin_retirement_'+name,[binary,*flags,'tests/regrtest/test_native_generator_pin_retirement.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('native_pin_retirement_'+name,[binary,*flags,'tests/regrtest/test_native_pin_retirement.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('native_slice_bounds_'+name,[binary,*flags,'tests/regrtest/test_native_slice_bounds.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='native slice bounds: ok\n')
    run('default_suffix_'+name,[binary,*flags,'tests/regrtest/test_default_suffix.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='default suffix semantics: ok\n')
    run('lazy_code_caches_'+name,[binary,*flags,'tests/regrtest/test_lazy_code_caches.py'],env={**os.environ,'WEAVEPY_JIT':jit},expected='lazy code cache semantics: ok\n')
    run('class_version_tokens_'+name,[binary,*flags,'tests/regrtest/test_class_version_tokens.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('indexed_slot_access_'+name,[binary,*flags,'tests/regrtest/test_indexed_slot_access.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('type_cache_names_'+name,[binary,*flags,'tests/regrtest/test_type_cache_names.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('jit_scalar_leaf_calls_'+name,[binary,*flags,'tests/regrtest/test_jit_scalar_leaf_calls.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('jit_unboxed_calls_'+name,[binary,*flags,'tests/regrtest/test_jit_unboxed_calls.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('jit_scalar_results_'+name,[binary,*flags,'tests/regrtest/test_jit_scalar_results.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('jit_constants_'+name,[binary,*flags,'tests/regrtest/test_jit_constants.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('small_slot_storage_'+name,[binary,*flags,'tests/regrtest/test_small_slot_storage.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('tuple_hash_cache_'+name,[binary,*flags,'tests/regrtest/test_tuple_hash_cache.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('hash_results_'+name,[binary,*flags,'tests/regrtest/test_hash_results.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('tuple_storage_'+name,[binary,*flags,'tests/regrtest/test_tuple_storage.py'],env={**os.environ,'WEAVEPY_JIT':jit},expected='ok\n')
    run('instance_metadata_'+name,[binary,*flags,'tests/regrtest/test_instance_metadata.py'],env={**os.environ,'WEAVEPY_JIT':jit},expected='ok\n')
    run('jit_list_lifetime_'+name,[binary,*flags,'tests/regrtest/test_jit_list_lifetime.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('jit_list_builders_'+name,[binary,*flags,'tests/regrtest/test_jit_list_builders.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'},expected='ok\n')
    run('jit_enumerate_'+name,[binary,*flags,'tests/regrtest/test_jit_enumerate.py'],env={**os.environ,'WEAVEPY_JIT':jit,'WEAVEPY_JIT_THRESHOLD':'3'})
    run('float_text_'+name,[binary,*flags,'tests/regrtest/test_float_text.py'],env={**os.environ,'WEAVEPY_JIT':jit})
    run('key_comparison_'+name,[binary,*flags,'tests/regrtest/test_key_comparison_state.py'],env={**os.environ,'WEAVEPY_JIT':jit})
    run('collections_datetime_'+name,[binary,*flags,'tests/regrtest/test_collections_datetime_fastpaths.py'],env={**os.environ,'WEAVEPY_JIT':jit})
    run('json_buffers_'+name,[binary,*flags,'tests/regrtest/test_json_buffers.py'],env={**os.environ,'WEAVEPY_JIT':jit})
    run('string_fastpaths_'+name,[binary,*flags,'tests/regrtest/test_string_fastpaths.py'],env={**os.environ,'WEAVEPY_JIT':jit})
run('cpython_datetime_oracles',['python3.14','crates/weavepy-bench/census/2026-09-collections-datetime/verify.py','--weavepy',binary,'--base',str(root/'target/release/weavepy-perf-9a69c41'),'--out',str(output.parent/'oracles.json')])
run('cpython_float_oracles',['python3.14','crates/weavepy-bench/census/2026-09-runtime-metadata/verify_float.py','--base',str(root/'target/release/weavepy-perf-9a69c41'),'--new',binary,'--samples','250000','--out',str(output.parent/'float-oracle.json')],timeout=900)
for test in ['test_frame_recycling', 'test_cross_thread_heap', 'test_threading_primitives', 'test_ws4_gc_cascade', 'test_pickle_callables']:
    for jit in ['1', '0']:
        run(test+'_jit'+jit,[binary,'tests/regrtest/'+test+'.py'],env={**os.environ,'WEAVEPY_JIT':jit})
    run(test+'_gil0',[binary,'-X','gil=0','tests/regrtest/'+test+'.py'])
for test in ['test_jit_object_lanes', 'test_jit_dyn_calls', 'test_jit_osr', 'test_jit_calls', 'test_jit_cells']:
    run(test,[binary,'tests/regrtest/'+test+'.py'])
run('gil0_runtime',[binary,'tests/regrtest/test_rfc0076_gil0.py'])
run('collections',[binary,'tests/regrtest/test_collections.py'])
run('queue_pingpong',[binary,'tests/regrtest/test_ws3_queue_pingpong.py'])
run('cpython_json_oracles',['python3.14','crates/weavepy-bench/census/2026-09-json/verify.py','--weavepy',binary])
for p in sorted((root/'crates/weavepy/tests/fixtures/run').glob('*.py')):
    if p.name.startswith('_'):continue
    source=p.read_text()
    if any('weavepy-skip:' in line and 'macos' in line for line in source.splitlines()[:20]):continue
    run('fixture/'+p.name,[binary,str(p)],expected=p.with_suffix('.out').read_text(),timeout=90)
for label in ['test_import','test_range','test_iter','test_iterlen','test_int','test_bool','test_hash','test_enumerate','test_tuple','test_genexps','test_list','test_float','test_complex','test_datetime','test_deque','test_collections','test_queue','test_json','test_scope','test_frame','test_exceptions','test_generators','test_sys_settrace','test_sys_setprofile','test_gc','test_str','test_userstring','test_type','test_dict','test_set','test_memoryview','test_io','test_pickle','test_weakref','test_threading','test_threading_local','test_monitoring','test_descr','test_class','test_functools','test_tracemalloc','test_capi/test_tuple' ]:
    run('cpython/'+label,['target/release/weavepy-conformance','regrtest',*(['--expectations',str(root/'crates/weavepy-bench/census/2026-09-runtime-metadata/tuple-capi-expectations.toml')] if label == 'test_capi/test_tuple' else []),*(['--all-cpython'] if label in {'test_bool', 'test_genexps', 'test_hash', 'test_functools', 'test_tracemalloc', 'test_capi/test_tuple'} else []),'--mode','subprocess','--weavepy',binary,'--filter','cpython/Lib/test/'+label+('.py' if label in {'test_import', 'test_range', 'test_iter', 'test_iterlen', 'test_hash', 'test_functools', 'test_tracemalloc', 'test_capi/test_tuple'} else ''),'--stream'],timeout=900)
print('PASSED',sum(r['passed'] for r in results),'OF',len(results),flush=True)
raise SystemExit(any(not r['passed'] for r in results))
