"""Make cache-free checkpoint copies while preserving the original local archives."""
import collections
import copy
import gzip
import io
import json
import tarfile
from prepare_performance_checkpoint import ROOT, sha, save

audit = json.loads((ROOT / 'target/performance-checkpoint-archive-verification.json').read_text())
selection_path = ROOT / 'target/performance-checkpoint-selection.json'
selection = json.loads(selection_path.read_text())
selected = set(selection['paths'])
groups = collections.defaultdict(set)
for row in audit['generated_members_to_exclude']:
    groups[row['archive']].add(row['member'])
for name, excluded in sorted(groups.items()):
    source = ROOT / name
    original_manifest = source.parent / 'MANIFEST.json'
    original_bytes = original_manifest.read_bytes()
    manifest = copy.deepcopy(json.loads(original_bytes))
    expected = manifest['archives'].pop(source.name)
    destination = source.parent / 'checkpoint-evidence.tar.gz'
    assert not destination.exists()
    members = {}
    with destination.open('xb') as raw:
        with gzip.GzipFile(filename='', mode='wb', fileobj=raw, mtime=0) as compressed:
            with tarfile.open(fileobj=compressed, mode='w|') as output:
                def add(member, data):
                    info = tarfile.TarInfo(member)
                    info.size = len(data)
                    info.mode = 0o644
                    output.addfile(info, io.BytesIO(data))
                    members[member] = {'bytes': len(data), 'sha256': sha(data)}
                with tarfile.open(source, 'r:gz') as original:
                    for info in original:
                        if info.name in excluded:
                            continue
                        data = original.extractfile(info).read()
                        assert len(data) == expected['members'][info.name]['bytes']
                        assert sha(data) == expected['members'][info.name]['sha256']
                        add(info.name, data)
                add('checkpoint-original-manifest.json', original_bytes)
    manifest['archives'][destination.name] = {'bytes': destination.stat().st_size, 'sha256': sha(destination.read_bytes()), 'members': members}
    manifest['checkpoint_filter'] = {
        'purpose': __doc__,
        'original_archive': {'name': source.name, 'bytes': expected['bytes'], 'sha256': expected['sha256']},
        'original_manifest_sha256': sha(original_bytes),
        'excluded_generated_members': sorted(excluded),
        'note': 'Only generated bytecode/cache members are omitted. Every remaining source, test, input, result, failure, and method retains its original bytes. The original manifest is inside the filtered archive. Historical reports and EXPORT logs describe the original archive; use this checkpoint manifest for the committed copies.',
    }
    save(source.parent / 'CHECKPOINT-MANIFEST.json', manifest)
    selected.remove(name)
    selected.remove(str(original_manifest.relative_to(ROOT)))
    selected.add(str(destination.relative_to(ROOT)))
    selected.add(str((source.parent / 'CHECKPOINT-MANIFEST.json').relative_to(ROOT)))
    print(source.parent.name, 'excluded', len(excluded), 'generated members; retained', len(members), flush=True)
selection['paths'] = sorted(selected)
selection['filtered_archive_cache_members'] = len(audit['generated_members_to_exclude'])
save(selection_path, selection)
