//! Build helper: embed the vendored CPython 3.13 header tree
//! (RFC 0062 WS2).
//!
//! The headers live in `crates/weavepy-capi/include/cpython314/` (the
//! stock CPython `Include/` install tree, PSF-licensed; see the
//! `LICENSE.txt` alongside them) plus the per-OS generated
//! `pyconfig.h` variants under `crates/weavepy-capi/include/pyconfig/`.
//! `stdlib_tree::materialize()` writes them into
//! `{prefix}/include/python3.14/` so `pip install` of an sdist with C
//! extensions can compile against the running interpreter — the same
//! layout a real CPython install ships.
//!
//! This script walks the tree and generates an
//! `include_str!`-backed table so the data rides inside the binary
//! (the same policy as the frozen stdlib sources).

use std::env;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[allow(unreachable_pub)] // The VM publicly re-exports the shared source type.
#[path = "src/stdlib/frozen_sources.rs"]
mod frozen_sources;
#[path = "src/stdlib/tree_manifest.rs"]
mod tree_manifest;

fn collect_headers(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = std::fs::read_dir(dir).unwrap_or_else(|e| {
        panic!(
            "cannot read vendored CPython header dir {}: {e}",
            dir.display()
        )
    });
    for entry in entries {
        let entry = entry.expect("read_dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_headers(&path, root, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("header path under root")
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((rel, path));
        }
    }
}

/// Canonicalize and stringify a path for embedding in generated Rust
/// source (the `{:?}` at the call site produces the quoted literal;
/// going through `&str` keeps clippy's Debug-on-Path lint quiet).
fn canonical_str(path: &Path, what: &str) -> String {
    let canonical = path
        .canonicalize()
        .unwrap_or_else(|e| panic!("{what}: {e}"));
    canonical
        .to_str()
        .unwrap_or_else(|| panic!("{what}: non-UTF-8 path {}", canonical.display()))
        .to_owned()
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let capi_include = manifest_dir
        .parent()
        .expect("crates/ dir")
        .join("weavepy-capi")
        .join("include");
    let tree = capi_include.join(weavepy_version::HEADER_TREE);
    println!("cargo:rerun-if-changed={}", tree.display());

    let mut headers = Vec::new();
    collect_headers(&tree, &tree, &mut headers);
    headers.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(
        headers.iter().any(|(rel, _)| rel == "Python.h"),
        "vendored CPython header tree is missing Python.h"
    );

    let mut src = String::new();
    src.push_str(
        "/// The vendored CPython 3.14 header tree, `/`-separated paths\n\
         /// relative to `include/python3.14/`. Generated by build.rs.\n\
         pub static CPYTHON_HEADERS: &[(&str, &str)] = &[\n",
    );
    for (rel, path) in &headers {
        writeln!(
            src,
            "    ({rel:?}, include_str!({:?})),",
            canonical_str(path, "canonical header path")
        )
        .unwrap();
    }
    src.push_str("];\n");

    // The one generated-per-platform file in a real install. POSIX
    // variants are real autoconf outputs; the Windows variant mirrors
    // CPython's hand-maintained `PC/pyconfig.h` (no autoconf on NT),
    // including the `python313.lib` MSVC autolink pragma (RFC 0064
    // WS3). `None` (other platforms) keeps the pre-0062 stub.
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let pyconfig = match target_os.as_str() {
        "macos" => Some(capi_include.join("pyconfig").join("pyconfig-macos.h")),
        "linux" | "freebsd" | "android" => {
            Some(capi_include.join("pyconfig").join("pyconfig-linux.h"))
        }
        "windows" => Some(capi_include.join("pyconfig").join("pyconfig-windows.h")),
        _ => None,
    };
    match pyconfig {
        Some(path) => {
            println!("cargo:rerun-if-changed={}", path.display());
            writeln!(
                src,
                "\n/// The generated `pyconfig.h` for this target platform.\n\
                 pub static PYCONFIG_H: Option<&str> = Some(include_str!({:?}));",
                canonical_str(&path, "canonical pyconfig path")
            )
            .unwrap();
        }
        None => {
            src.push_str(
                "\n/// The generated `pyconfig.h` for this target platform.\n\
                 pub static PYCONFIG_H: Option<&str> = None;\n",
            );
        }
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    // Track both the manifest and all included sources, including additions
    // and deletions. The runtime and build script share the same Rust table.
    for path in [
        "src/stdlib/frozen_sources.rs",
        "src/stdlib/tree_manifest.rs",
        "src/stdlib/python",
    ] {
        println!("cargo:rerun-if-changed={path}");
    }
    let build_id = tree_manifest::fingerprint(
        &env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION"),
        frozen_sources::frozen_sources(),
    );
    // The frozen-module name index: every name, sorted, in one contiguous
    // string. Each name literal in the table is laid out beside its
    // module's embedded source, so hashing the whole table at start-up
    // touched a page of source text per module; a lookup through the
    // index reads a few kilobytes. A repeated name resolves to its last
    // table row, as the registration map it replaces did.
    let mut names: Vec<(&str, usize)> = frozen_sources::frozen_sources()
        .iter()
        .enumerate()
        .map(|(i, s)| (s.name, i))
        .collect();
    names.sort_by(|a, b| a.0.cmp(b.0).then(a.1.cmp(&b.1)));
    names.dedup_by(|later, earlier| {
        let same = later.0 == earlier.0;
        if same {
            earlier.1 = later.1;
        }
        same
    });
    let mut blob = String::new();
    let mut index = String::new();
    for (name, row) in &names {
        writeln!(index, "    ({}, {}, {row}),", blob.len(), name.len()).unwrap();
        blob.push_str(name);
    }
    std::fs::write(
        out_dir.join("frozen_index.rs"),
        format!(
            "/// Every frozen-module name, sorted, concatenated (see build.rs).\n\
             pub(crate) static FROZEN_NAMES: &str = {blob:?};\n\
             /// `(offset, length)` of each name in [`FROZEN_NAMES`], in order,\n\
             /// with its row in `frozen_sources()`.\n\
             pub(crate) static FROZEN_INDEX: [(u32, u16, u16); {}] = [\n{index}];\n",
            names.len()
        ),
    )
    .expect("write frozen_index.rs");
    std::fs::write(
        out_dir.join("stdlib_build_id.rs"),
        format!(
            "0x{:04x}_{:04x}_{:04x}_{:04x}u64\n",
            build_id >> 48,
            (build_id >> 32) & 0xffff,
            (build_id >> 16) & 0xffff,
            build_id & 0xffff,
        ),
    )
    .expect("write stdlib_build_id.rs");
    std::fs::write(out_dir.join("cpython_headers.rs"), src).expect("write cpython_headers.rs");
}
