//! Build helper: embed the vendored CPython 3.13 header tree
//! (RFC 0062 WS2).
//!
//! The headers live in `crates/weavepy-capi/include/cpython313/` (the
//! stock CPython `Include/` install tree, PSF-licensed; see the
//! `LICENSE.txt` alongside them) plus the per-OS generated
//! `pyconfig.h` variants under `crates/weavepy-capi/include/pyconfig/`.
//! `stdlib_tree::materialize()` writes them into
//! `{prefix}/include/python3.13/` so `pip install` of an sdist with C
//! extensions can compile against the running interpreter — the same
//! layout a real CPython install ships.
//!
//! This script walks the tree and generates an
//! `include_str!`-backed table so the data rides inside the binary
//! (the same policy as the frozen stdlib sources).

use std::env;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn collect_headers(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = std::fs::read_dir(dir).unwrap_or_else(|e| {
        panic!(
            "cannot read vendored CPython header dir {}: {e}",
            dir.display()
        )
    });
    for entry in entries {
        let entry = entry.expect("read_dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_headers(&path, root, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("header path under root")
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((rel, path));
        }
    }
}

/// Canonicalize and stringify a path for embedding in generated Rust
/// source (the `{:?}` at the call site produces the quoted literal;
/// going through `&str` keeps clippy's Debug-on-Path lint quiet).
fn canonical_str(path: &Path, what: &str) -> String {
    let canonical = path
        .canonicalize()
        .unwrap_or_else(|e| panic!("{what}: {e}"));
    canonical
        .to_str()
        .unwrap_or_else(|| panic!("{what}: non-UTF-8 path {}", canonical.display()))
        .to_owned()
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let capi_include = manifest_dir
        .parent()
        .expect("crates/ dir")
        .join("weavepy-capi")
        .join("include");
    let tree = capi_include.join("cpython313");
    println!("cargo:rerun-if-changed={}", tree.display());

    let mut headers = Vec::new();
    collect_headers(&tree, &tree, &mut headers);
    headers.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(
        headers.iter().any(|(rel, _)| rel == "Python.h"),
        "vendored CPython header tree is missing Python.h"
    );

    let mut src = String::new();
    src.push_str(
        "/// The vendored CPython 3.13 header tree, `/`-separated paths\n\
         /// relative to `include/python3.13/`. Generated by build.rs.\n\
         pub static CPYTHON_HEADERS: &[(&str, &str)] = &[\n",
    );
    for (rel, path) in &headers {
        writeln!(
            src,
            "    ({rel:?}, include_str!({:?})),",
            canonical_str(path, "canonical header path")
        )
        .unwrap();
    }
    src.push_str("];\n");

    // The one generated-per-platform file in a real install. POSIX
    // variants are real autoconf outputs; the Windows variant mirrors
    // CPython's hand-maintained `PC/pyconfig.h` (no autoconf on NT),
    // including the `python313.lib` MSVC autolink pragma (RFC 0064
    // WS3). `None` (other platforms) keeps the pre-0062 stub.
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let pyconfig = match target_os.as_str() {
        "macos" => Some(capi_include.join("pyconfig").join("pyconfig-macos.h")),
        "linux" | "freebsd" | "android" => {
            Some(capi_include.join("pyconfig").join("pyconfig-linux.h"))
        }
        "windows" => Some(capi_include.join("pyconfig").join("pyconfig-windows.h")),
        _ => None,
    };
    match pyconfig {
        Some(path) => {
            println!("cargo:rerun-if-changed={}", path.display());
            writeln!(
                src,
                "\n/// The generated `pyconfig.h` for this target platform.\n\
                 pub static PYCONFIG_H: Option<&str> = Some(include_str!({:?}));",
                canonical_str(&path, "canonical pyconfig path")
            )
            .unwrap();
        }
        None => {
            src.push_str(
                "\n/// The generated `pyconfig.h` for this target platform.\n\
                 pub static PYCONFIG_H: Option<&str> = None;\n",
            );
        }
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("cpython_headers.rs"), src).expect("write cpython_headers.rs");
}
