[package]
name = "weavepy-version"
description = "The single source of the CPython version WeavePy implements (RFC 0077 WS12)."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
readme.workspace       = true
keywords.workspace     = true
categories.workspace   = true

[dependencies]

[lints]
workspace = true
