"""``ensurepip`` — bootstrap a working ``pip`` into a venv.

WeavePy ships a minimal pip (``_minipip``) that can install
pure-Python wheels from PyPI or a local path. Once it bootstraps,
the user can ``pip install pip`` to upgrade to real upstream pip.

The surface here mirrors CPython's ``Lib/ensurepip/__init__.py``:

    >>> import ensurepip
    >>> ensurepip.bootstrap()

We deliberately do **not** vendor a full upstream pip wheel — that
would multiply the binary size by ~3 MiB and adds version drift.
The bundled `_minipip` is small enough (≈900 LOC of Python) to
ship inline.
"""

import os
import sys

__all__ = ['version', 'bootstrap']

_PIP_VERSION = '0.1.0+weavepy'


def version():
    return _PIP_VERSION


def _site_packages_for(env_dir):
    py = 'python%d.%d' % sys.version_info[:2]
    if os.name == 'nt':
        return os.path.join(env_dir, 'Lib', 'site-packages')
    return os.path.join(env_dir, 'lib', py, 'site-packages')


def _write_pip_shim(env_dir):
    if os.name == 'nt':
        target = os.path.join(env_dir, 'Scripts', 'pip.bat')
        body = ('@echo off\r\n'
                '"%~dp0python.exe" -m _minipip %*\r\n')
    else:
        target = os.path.join(env_dir, 'bin', 'pip')
        py = os.path.join(env_dir, 'bin', 'python')
        body = ('#!/usr/bin/env sh\n'
                'exec "{}" -m _minipip "$@"\n'.format(py))
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, 'w', encoding='utf-8') as f:
        f.write(body)
    if os.name != 'nt':
        try:
            os.chmod(target, 0o755)
        except OSError:
            pass
    # ``pip3`` alias.
    if os.name != 'nt':
        alias = target + '3'
        try:
            if os.path.lexists(alias):
                os.remove(alias)
        except OSError:
            pass
        try:
            os.symlink(os.path.basename(target), alias)
        except OSError:
            try:
                with open(alias, 'w', encoding='utf-8') as f:
                    f.write(body)
                os.chmod(alias, 0o755)
            except OSError:
                pass


def _install_minipip_stub(site_packages):
    """Drop a tiny ``_minipip`` re-export into the venv's site-packages.

    The actual implementation lives as a frozen module in the
    WeavePy binary; the stub just `import _minipip; sys.exit(_minipip.main())`.
    Users who want to ship pip independently can ``pip install pip``
    once this bootstraps.
    """
    os.makedirs(site_packages, exist_ok=True)
    stub = os.path.join(site_packages, 'pip_shim.py')
    body = (
        "# Auto-generated by WeavePy ensurepip.\n"
        "from _minipip import main\n"
    )
    try:
        with open(stub, 'w', encoding='utf-8') as f:
            f.write(body)
    except OSError:
        pass


def bootstrap(*, root=None, upgrade=False, user=False,
                altinstall=False, default_pip=False, verbosity=0,
                env_dir=None, symlinks=False):
    """Install the WeavePy minimal pip into ``env_dir``.

    Most arguments are accepted for CLI-shape compatibility but
    have no observable effect today.
    """
    if env_dir is None:
        env_dir = sys.prefix
    site_packages = _site_packages_for(env_dir)
    _install_minipip_stub(site_packages)
    _write_pip_shim(env_dir)


def _main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(prog='ensurepip')
    parser.add_argument('--version', action='store_true')
    parser.add_argument('--root', default=None)
    parser.add_argument('-U', '--upgrade', action='store_true')
    parser.add_argument('--user', action='store_true')
    parser.add_argument('--altinstall', action='store_true')
    parser.add_argument('--default-pip', action='store_true')
    opts = parser.parse_args(argv)
    if opts.version:
        print(version())
        return 0
    bootstrap(root=opts.root, upgrade=opts.upgrade, user=opts.user,
                altinstall=opts.altinstall, default_pip=opts.default_pip)
    return 0


if __name__ == '__main__':
    sys.exit(_main(sys.argv[1:]))
