"""opcode — CPython 3.13 opcode tables (RFC 0033).

Self-contained: derived from CPython 3.13's opcode/_opcode data so
`dis` and other tools see CPython-faithful numbers. WeavePy emits only
canonical (non-specialized) opcodes, so the specialization tables are
intentionally empty."""

__all__ = ["cmp_op", "stack_effect", "hascompare", "opname", "opmap",
           "HAVE_ARGUMENT", "EXTENDED_ARG", "hasarg", "hasconst", "hasname",
           "hasjump", "hasjrel", "hasjabs", "hasfree", "haslocal", "hasexc"]

opmap = {
    'CACHE': 0,
    'RESERVED': 17,
    'RESUME': 149,
    'INSTRUMENTED_LINE': 254,
    'BEFORE_ASYNC_WITH': 1,
    'BEFORE_WITH': 2,
    'BINARY_SLICE': 4,
    'BINARY_SUBSCR': 5,
    'CHECK_EG_MATCH': 6,
    'CHECK_EXC_MATCH': 7,
    'CLEANUP_THROW': 8,
    'DELETE_SUBSCR': 9,
    'END_ASYNC_FOR': 10,
    'END_FOR': 11,
    'END_SEND': 12,
    'EXIT_INIT_CHECK': 13,
    'FORMAT_SIMPLE': 14,
    'FORMAT_WITH_SPEC': 15,
    'GET_AITER': 16,
    'GET_ANEXT': 18,
    'GET_ITER': 19,
    'GET_LEN': 20,
    'GET_YIELD_FROM_ITER': 21,
    'INTERPRETER_EXIT': 22,
    'LOAD_ASSERTION_ERROR': 23,
    'LOAD_BUILD_CLASS': 24,
    'LOAD_LOCALS': 25,
    'MAKE_FUNCTION': 26,
    'MATCH_KEYS': 27,
    'MATCH_MAPPING': 28,
    'MATCH_SEQUENCE': 29,
    'NOP': 30,
    'POP_EXCEPT': 31,
    'POP_TOP': 32,
    'PUSH_EXC_INFO': 33,
    'PUSH_NULL': 34,
    'RETURN_GENERATOR': 35,
    'RETURN_VALUE': 36,
    'SETUP_ANNOTATIONS': 37,
    'STORE_SLICE': 38,
    'STORE_SUBSCR': 39,
    'TO_BOOL': 40,
    'UNARY_INVERT': 41,
    'UNARY_NEGATIVE': 42,
    'UNARY_NOT': 43,
    'WITH_EXCEPT_START': 44,
    'BINARY_OP': 45,
    'BUILD_CONST_KEY_MAP': 46,
    'BUILD_LIST': 47,
    'BUILD_MAP': 48,
    'BUILD_SET': 49,
    'BUILD_SLICE': 50,
    'BUILD_STRING': 51,
    'BUILD_TUPLE': 52,
    'CALL': 53,
    'CALL_FUNCTION_EX': 54,
    'CALL_INTRINSIC_1': 55,
    'CALL_INTRINSIC_2': 56,
    'CALL_KW': 57,
    'COMPARE_OP': 58,
    'CONTAINS_OP': 59,
    'CONVERT_VALUE': 60,
    'COPY': 61,
    'COPY_FREE_VARS': 62,
    'DELETE_ATTR': 63,
    'DELETE_DEREF': 64,
    'DELETE_FAST': 65,
    'DELETE_GLOBAL': 66,
    'DELETE_NAME': 67,
    'DICT_MERGE': 68,
    'DICT_UPDATE': 69,
    'ENTER_EXECUTOR': 70,
    'EXTENDED_ARG': 71,
    'FOR_ITER': 72,
    'GET_AWAITABLE': 73,
    'IMPORT_FROM': 74,
    'IMPORT_NAME': 75,
    'IS_OP': 76,
    'JUMP_BACKWARD': 77,
    'JUMP_BACKWARD_NO_INTERRUPT': 78,
    'JUMP_FORWARD': 79,
    'LIST_APPEND': 80,
    'LIST_EXTEND': 81,
    'LOAD_ATTR': 82,
    'LOAD_CONST': 83,
    'LOAD_DEREF': 84,
    'LOAD_FAST': 85,
    'LOAD_FAST_AND_CLEAR': 86,
    'LOAD_FAST_CHECK': 87,
    'LOAD_FAST_LOAD_FAST': 88,
    'LOAD_FROM_DICT_OR_DEREF': 89,
    'LOAD_FROM_DICT_OR_GLOBALS': 90,
    'LOAD_GLOBAL': 91,
    'LOAD_NAME': 92,
    'LOAD_SUPER_ATTR': 93,
    'MAKE_CELL': 94,
    'MAP_ADD': 95,
    'MATCH_CLASS': 96,
    'POP_JUMP_IF_FALSE': 97,
    'POP_JUMP_IF_NONE': 98,
    'POP_JUMP_IF_NOT_NONE': 99,
    'POP_JUMP_IF_TRUE': 100,
    'RAISE_VARARGS': 101,
    'RERAISE': 102,
    'RETURN_CONST': 103,
    'SEND': 104,
    'SET_ADD': 105,
    'SET_FUNCTION_ATTRIBUTE': 106,
    'SET_UPDATE': 107,
    'STORE_ATTR': 108,
    'STORE_DEREF': 109,
    'STORE_FAST': 110,
    'STORE_FAST_LOAD_FAST': 111,
    'STORE_FAST_STORE_FAST': 112,
    'STORE_GLOBAL': 113,
    'STORE_NAME': 114,
    'SWAP': 115,
    'UNPACK_EX': 116,
    'UNPACK_SEQUENCE': 117,
    'YIELD_VALUE': 118,
    'INSTRUMENTED_RESUME': 236,
    'INSTRUMENTED_END_FOR': 237,
    'INSTRUMENTED_END_SEND': 238,
    'INSTRUMENTED_RETURN_VALUE': 239,
    'INSTRUMENTED_RETURN_CONST': 240,
    'INSTRUMENTED_YIELD_VALUE': 241,
    'INSTRUMENTED_LOAD_SUPER_ATTR': 242,
    'INSTRUMENTED_FOR_ITER': 243,
    'INSTRUMENTED_CALL': 244,
    'INSTRUMENTED_CALL_KW': 245,
    'INSTRUMENTED_CALL_FUNCTION_EX': 246,
    'INSTRUMENTED_INSTRUCTION': 247,
    'INSTRUMENTED_JUMP_FORWARD': 248,
    'INSTRUMENTED_JUMP_BACKWARD': 249,
    'INSTRUMENTED_POP_JUMP_IF_TRUE': 250,
    'INSTRUMENTED_POP_JUMP_IF_FALSE': 251,
    'INSTRUMENTED_POP_JUMP_IF_NONE': 252,
    'INSTRUMENTED_POP_JUMP_IF_NOT_NONE': 253,
    'JUMP': 256,
    'JUMP_NO_INTERRUPT': 257,
    'LOAD_CLOSURE': 258,
    'LOAD_METHOD': 259,
    'LOAD_SUPER_METHOD': 260,
    'LOAD_ZERO_SUPER_ATTR': 261,
    'LOAD_ZERO_SUPER_METHOD': 262,
    'POP_BLOCK': 263,
    'SETUP_CLEANUP': 264,
    'SETUP_FINALLY': 265,
    'SETUP_WITH': 266,
    'STORE_FAST_MAYBE_NULL': 267,
}

HAVE_ARGUMENT = 44
MIN_INSTRUMENTED_OPCODE = 236
EXTENDED_ARG = opmap['EXTENDED_ARG']

opname = ['<%r>' % (op,) for op in range(max(opmap.values()) + 1)]
for _op, _i in opmap.items():
    opname[_i] = _op

cmp_op = ('<', '<=', '==', '!=', '>', '>=')

hasarg = [149, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 236, 240, 241, 242, 243, 244, 245, 248, 249, 250, 251, 252, 253, 256, 257, 258, 259, 260, 261, 262, 264, 265, 266, 267]
hasconst = [83, 103, 240]
hasname = [63, 66, 67, 74, 75, 82, 90, 91, 92, 93, 108, 113, 114, 259, 260, 261, 262]
hasjrel = [72, 77, 78, 79, 97, 98, 99, 100, 104, 256, 257]
hasjabs = []
hasfree = [64, 84, 89, 94, 109]
haslocal = [65, 85, 86, 87, 88, 110, 111, 112, 258, 267]
hasexc = [264, 265, 266]
hasjump = hasjrel
hascompare = [opmap["COMPARE_OP"]]

_nb_ops = [('NB_ADD', '+'), ('NB_AND', '&'), ('NB_FLOOR_DIVIDE', '//'), ('NB_LSHIFT', '<<'), ('NB_MATRIX_MULTIPLY', '@'), ('NB_MULTIPLY', '*'), ('NB_REMAINDER', '%'), ('NB_OR', '|'), ('NB_POWER', '**'), ('NB_RSHIFT', '>>'), ('NB_SUBTRACT', '-'), ('NB_TRUE_DIVIDE', '/'), ('NB_XOR', '^'), ('NB_INPLACE_ADD', '+='), ('NB_INPLACE_AND', '&='), ('NB_INPLACE_FLOOR_DIVIDE', '//='), ('NB_INPLACE_LSHIFT', '<<='), ('NB_INPLACE_MATRIX_MULTIPLY', '@='), ('NB_INPLACE_MULTIPLY', '*='), ('NB_INPLACE_REMAINDER', '%='), ('NB_INPLACE_OR', '|='), ('NB_INPLACE_POWER', '**='), ('NB_INPLACE_RSHIFT', '>>='), ('NB_INPLACE_SUBTRACT', '-='), ('NB_INPLACE_TRUE_DIVIDE', '/='), ('NB_INPLACE_XOR', '^=')]
_intrinsic_1_descs = ['INTRINSIC_1_INVALID', 'INTRINSIC_PRINT', 'INTRINSIC_IMPORT_STAR', 'INTRINSIC_STOPITERATION_ERROR', 'INTRINSIC_ASYNC_GEN_WRAP', 'INTRINSIC_UNARY_POSITIVE', 'INTRINSIC_LIST_TO_TUPLE', 'INTRINSIC_TYPEVAR', 'INTRINSIC_PARAMSPEC', 'INTRINSIC_TYPEVARTUPLE', 'INTRINSIC_SUBSCRIPT_GENERIC', 'INTRINSIC_TYPEALIAS']
_intrinsic_2_descs = ['INTRINSIC_2_INVALID', 'INTRINSIC_PREP_RERAISE_STAR', 'INTRINSIC_TYPEVAR_WITH_BOUND', 'INTRINSIC_TYPEVAR_WITH_CONSTRAINTS', 'INTRINSIC_SET_FUNCTION_TYPE_PARAMS', 'INTRINSIC_SET_TYPEPARAM_DEFAULT']

# CPython 3.13's specialization families (from `_opcode_metadata.py`).
# WeavePy never *emits* adaptive/specialized opcodes, but `dis` builds
# `deoptmap` from these and `test.support` probes them, so the tables
# must be CPython-faithful.
_specializations = {
    "RESUME": [
        "RESUME_CHECK",
    ],
    "TO_BOOL": [
        "TO_BOOL_ALWAYS_TRUE",
        "TO_BOOL_BOOL",
        "TO_BOOL_INT",
        "TO_BOOL_LIST",
        "TO_BOOL_NONE",
        "TO_BOOL_STR",
    ],
    "BINARY_OP": [
        "BINARY_OP_MULTIPLY_INT",
        "BINARY_OP_ADD_INT",
        "BINARY_OP_SUBTRACT_INT",
        "BINARY_OP_MULTIPLY_FLOAT",
        "BINARY_OP_ADD_FLOAT",
        "BINARY_OP_SUBTRACT_FLOAT",
        "BINARY_OP_ADD_UNICODE",
        "BINARY_OP_INPLACE_ADD_UNICODE",
    ],
    "BINARY_SUBSCR": [
        "BINARY_SUBSCR_DICT",
        "BINARY_SUBSCR_GETITEM",
        "BINARY_SUBSCR_LIST_INT",
        "BINARY_SUBSCR_STR_INT",
        "BINARY_SUBSCR_TUPLE_INT",
    ],
    "STORE_SUBSCR": [
        "STORE_SUBSCR_DICT",
        "STORE_SUBSCR_LIST_INT",
    ],
    "SEND": [
        "SEND_GEN",
    ],
    "UNPACK_SEQUENCE": [
        "UNPACK_SEQUENCE_TWO_TUPLE",
        "UNPACK_SEQUENCE_TUPLE",
        "UNPACK_SEQUENCE_LIST",
    ],
    "STORE_ATTR": [
        "STORE_ATTR_INSTANCE_VALUE",
        "STORE_ATTR_SLOT",
        "STORE_ATTR_WITH_HINT",
    ],
    "LOAD_GLOBAL": [
        "LOAD_GLOBAL_MODULE",
        "LOAD_GLOBAL_BUILTIN",
    ],
    "LOAD_SUPER_ATTR": [
        "LOAD_SUPER_ATTR_ATTR",
        "LOAD_SUPER_ATTR_METHOD",
    ],
    "LOAD_ATTR": [
        "LOAD_ATTR_INSTANCE_VALUE",
        "LOAD_ATTR_MODULE",
        "LOAD_ATTR_WITH_HINT",
        "LOAD_ATTR_SLOT",
        "LOAD_ATTR_CLASS",
        "LOAD_ATTR_PROPERTY",
        "LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN",
        "LOAD_ATTR_METHOD_WITH_VALUES",
        "LOAD_ATTR_METHOD_NO_DICT",
        "LOAD_ATTR_METHOD_LAZY_DICT",
        "LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES",
        "LOAD_ATTR_NONDESCRIPTOR_NO_DICT",
    ],
    "COMPARE_OP": [
        "COMPARE_OP_FLOAT",
        "COMPARE_OP_INT",
        "COMPARE_OP_STR",
    ],
    "CONTAINS_OP": [
        "CONTAINS_OP_SET",
        "CONTAINS_OP_DICT",
    ],
    "FOR_ITER": [
        "FOR_ITER_LIST",
        "FOR_ITER_TUPLE",
        "FOR_ITER_RANGE",
        "FOR_ITER_GEN",
    ],
    "CALL": [
        "CALL_BOUND_METHOD_EXACT_ARGS",
        "CALL_PY_EXACT_ARGS",
        "CALL_TYPE_1",
        "CALL_STR_1",
        "CALL_TUPLE_1",
        "CALL_BUILTIN_CLASS",
        "CALL_BUILTIN_O",
        "CALL_BUILTIN_FAST",
        "CALL_BUILTIN_FAST_WITH_KEYWORDS",
        "CALL_LEN",
        "CALL_ISINSTANCE",
        "CALL_LIST_APPEND",
        "CALL_METHOD_DESCRIPTOR_O",
        "CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS",
        "CALL_METHOD_DESCRIPTOR_NOARGS",
        "CALL_METHOD_DESCRIPTOR_FAST",
        "CALL_ALLOC_AND_ENTER_INIT",
        "CALL_PY_GENERAL",
        "CALL_BOUND_METHOD_GENERAL",
        "CALL_NON_PY_GENERAL",
    ],
}

_specialized_opmap = {
    'BINARY_OP_ADD_FLOAT': 150,
    'BINARY_OP_ADD_INT': 151,
    'BINARY_OP_ADD_UNICODE': 152,
    'BINARY_OP_INPLACE_ADD_UNICODE': 3,
    'BINARY_OP_MULTIPLY_FLOAT': 153,
    'BINARY_OP_MULTIPLY_INT': 154,
    'BINARY_OP_SUBTRACT_FLOAT': 155,
    'BINARY_OP_SUBTRACT_INT': 156,
    'BINARY_SUBSCR_DICT': 157,
    'BINARY_SUBSCR_GETITEM': 158,
    'BINARY_SUBSCR_LIST_INT': 159,
    'BINARY_SUBSCR_STR_INT': 160,
    'BINARY_SUBSCR_TUPLE_INT': 161,
    'CALL_ALLOC_AND_ENTER_INIT': 162,
    'CALL_BOUND_METHOD_EXACT_ARGS': 163,
    'CALL_BOUND_METHOD_GENERAL': 164,
    'CALL_BUILTIN_CLASS': 165,
    'CALL_BUILTIN_FAST': 166,
    'CALL_BUILTIN_FAST_WITH_KEYWORDS': 167,
    'CALL_BUILTIN_O': 168,
    'CALL_ISINSTANCE': 169,
    'CALL_LEN': 170,
    'CALL_LIST_APPEND': 171,
    'CALL_METHOD_DESCRIPTOR_FAST': 172,
    'CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS': 173,
    'CALL_METHOD_DESCRIPTOR_NOARGS': 174,
    'CALL_METHOD_DESCRIPTOR_O': 175,
    'CALL_NON_PY_GENERAL': 176,
    'CALL_PY_EXACT_ARGS': 177,
    'CALL_PY_GENERAL': 178,
    'CALL_STR_1': 179,
    'CALL_TUPLE_1': 180,
    'CALL_TYPE_1': 181,
    'COMPARE_OP_FLOAT': 182,
    'COMPARE_OP_INT': 183,
    'COMPARE_OP_STR': 184,
    'CONTAINS_OP_DICT': 185,
    'CONTAINS_OP_SET': 186,
    'FOR_ITER_GEN': 187,
    'FOR_ITER_LIST': 188,
    'FOR_ITER_RANGE': 189,
    'FOR_ITER_TUPLE': 190,
    'LOAD_ATTR_CLASS': 191,
    'LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN': 192,
    'LOAD_ATTR_INSTANCE_VALUE': 193,
    'LOAD_ATTR_METHOD_LAZY_DICT': 194,
    'LOAD_ATTR_METHOD_NO_DICT': 195,
    'LOAD_ATTR_METHOD_WITH_VALUES': 196,
    'LOAD_ATTR_MODULE': 197,
    'LOAD_ATTR_NONDESCRIPTOR_NO_DICT': 198,
    'LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES': 199,
    'LOAD_ATTR_PROPERTY': 200,
    'LOAD_ATTR_SLOT': 201,
    'LOAD_ATTR_WITH_HINT': 202,
    'LOAD_GLOBAL_BUILTIN': 203,
    'LOAD_GLOBAL_MODULE': 204,
    'LOAD_SUPER_ATTR_ATTR': 205,
    'LOAD_SUPER_ATTR_METHOD': 206,
    'RESUME_CHECK': 207,
    'SEND_GEN': 208,
    'STORE_ATTR_INSTANCE_VALUE': 209,
    'STORE_ATTR_SLOT': 210,
    'STORE_ATTR_WITH_HINT': 211,
    'STORE_SUBSCR_DICT': 212,
    'STORE_SUBSCR_LIST_INT': 213,
    'TO_BOOL_ALWAYS_TRUE': 214,
    'TO_BOOL_BOOL': 215,
    'TO_BOOL_INT': 216,
    'TO_BOOL_LIST': 217,
    'TO_BOOL_NONE': 218,
    'TO_BOOL_STR': 219,
    'UNPACK_SEQUENCE_LIST': 220,
    'UNPACK_SEQUENCE_TUPLE': 221,
    'UNPACK_SEQUENCE_TWO_TUPLE': 222,
}

_cache_format = {
    'LOAD_GLOBAL': {'counter': 1, 'index': 1, 'module_keys_version': 1, 'builtin_keys_version': 1},
    'BINARY_OP': {'counter': 1},
    'UNPACK_SEQUENCE': {'counter': 1},
    'COMPARE_OP': {'counter': 1},
    'CONTAINS_OP': {'counter': 1},
    'BINARY_SUBSCR': {'counter': 1},
    'FOR_ITER': {'counter': 1},
    'LOAD_SUPER_ATTR': {'counter': 1},
    'LOAD_ATTR': {'counter': 1, 'version': 2, 'keys_version': 2, 'descr': 4},
    'STORE_ATTR': {'counter': 1, 'version': 2, 'index': 1},
    'CALL': {'counter': 1, 'func_version': 2},
    'STORE_SUBSCR': {'counter': 1},
    'SEND': {'counter': 1},
    'JUMP_BACKWARD': {'counter': 1},
    'TO_BOOL': {'counter': 1, 'version': 2},
    'POP_JUMP_IF_TRUE': {'counter': 1},
    'POP_JUMP_IF_FALSE': {'counter': 1},
    'POP_JUMP_IF_NONE': {'counter': 1},
    'POP_JUMP_IF_NOT_NONE': {'counter': 1},
}

_inline_cache_entries = {
    name: sum(value.values()) for (name, value) in _cache_format.items()
}


# Net stack effect per opcode, transcribed from CPython 3.13's generated
# `_PyOpcode_num_pushed - _PyOpcode_num_popped` metadata
# (Include/internal/pycore_opcode_metadata.h). Formulas whose oparg terms
# cancel (e.g. LIST_APPEND pops 2+(oparg-1), pushes 1+(oparg-1)) are
# folded to their constant value.
_stack_effects = {
    'BEFORE_ASYNC_WITH': 1,
    'BEFORE_WITH': 1,
    'BINARY_OP': -1,
    'BINARY_SLICE': -2,
    'BINARY_SUBSCR': -1,
    'CACHE': 0,
    'CALL_INTRINSIC_1': 0,
    'CALL_INTRINSIC_2': -1,
    'CHECK_EG_MATCH': 0,
    'CHECK_EXC_MATCH': 0,
    'CLEANUP_THROW': -1,
    'COMPARE_OP': -1,
    'CONTAINS_OP': -1,
    'CONVERT_VALUE': 0,
    'COPY': 1,
    'COPY_FREE_VARS': 0,
    'DELETE_ATTR': -1,
    'DELETE_DEREF': 0,
    'DELETE_FAST': 0,
    'DELETE_GLOBAL': 0,
    'DELETE_NAME': 0,
    'DELETE_SUBSCR': -2,
    'DICT_MERGE': -1,
    'DICT_UPDATE': -1,
    'END_ASYNC_FOR': -2,
    'END_FOR': -1,
    'END_SEND': -1,
    'ENTER_EXECUTOR': 0,
    'EXIT_INIT_CHECK': -1,
    'EXTENDED_ARG': 0,
    'FORMAT_SIMPLE': 0,
    'FORMAT_WITH_SPEC': -1,
    'FOR_ITER': 1,
    'GET_AITER': 0,
    'GET_ANEXT': 1,
    'GET_AWAITABLE': 0,
    'GET_ITER': 0,
    'GET_LEN': 1,
    'GET_YIELD_FROM_ITER': 0,
    'IMPORT_FROM': 1,
    'IMPORT_NAME': -1,
    'INSTRUMENTED_CALL': 0,
    'INSTRUMENTED_CALL_FUNCTION_EX': 0,
    'INSTRUMENTED_CALL_KW': 0,
    'INSTRUMENTED_END_FOR': -1,
    'INSTRUMENTED_END_SEND': -1,
    'INSTRUMENTED_FOR_ITER': 0,
    'INSTRUMENTED_INSTRUCTION': 0,
    'INSTRUMENTED_JUMP_BACKWARD': 0,
    'INSTRUMENTED_JUMP_FORWARD': 0,
    'INSTRUMENTED_POP_JUMP_IF_FALSE': 0,
    'INSTRUMENTED_POP_JUMP_IF_NONE': 0,
    'INSTRUMENTED_POP_JUMP_IF_NOT_NONE': 0,
    'INSTRUMENTED_POP_JUMP_IF_TRUE': 0,
    'INSTRUMENTED_RESUME': 0,
    'INSTRUMENTED_RETURN_CONST': 0,
    'INSTRUMENTED_RETURN_VALUE': -1,
    'INSTRUMENTED_YIELD_VALUE': 0,
    'INTERPRETER_EXIT': -1,
    'IS_OP': -1,
    'JUMP_BACKWARD': 0,
    'JUMP_BACKWARD_NO_INTERRUPT': 0,
    'JUMP_FORWARD': 0,
    'LIST_APPEND': -1,
    'LIST_EXTEND': -1,
    'LOAD_ASSERTION_ERROR': 1,
    'LOAD_BUILD_CLASS': 1,
    'LOAD_CONST': 1,
    'LOAD_DEREF': 1,
    'LOAD_FAST': 1,
    'LOAD_FAST_AND_CLEAR': 1,
    'LOAD_FAST_CHECK': 1,
    'LOAD_FAST_LOAD_FAST': 2,
    'LOAD_FROM_DICT_OR_DEREF': 0,
    'LOAD_FROM_DICT_OR_GLOBALS': 0,
    'LOAD_LOCALS': 1,
    'LOAD_NAME': 1,
    'MAKE_CELL': 0,
    'MAKE_FUNCTION': 0,
    'MAP_ADD': -2,
    'MATCH_CLASS': -2,
    'MATCH_KEYS': 1,
    'MATCH_MAPPING': 1,
    'MATCH_SEQUENCE': 1,
    'NOP': 0,
    'POP_EXCEPT': -1,
    'POP_JUMP_IF_FALSE': -1,
    'POP_JUMP_IF_NONE': -1,
    'POP_JUMP_IF_NOT_NONE': -1,
    'POP_JUMP_IF_TRUE': -1,
    'POP_TOP': -1,
    'PUSH_EXC_INFO': 1,
    'PUSH_NULL': 1,
    'RERAISE': -1,
    'RESERVED': 0,
    'RESUME': 0,
    'RETURN_CONST': 0,
    'RETURN_GENERATOR': 1,
    'RETURN_VALUE': -1,
    'SEND': 0,
    'SETUP_ANNOTATIONS': 0,
    'SET_ADD': -1,
    'SET_FUNCTION_ATTRIBUTE': -1,
    'SET_UPDATE': -1,
    'STORE_ATTR': -2,
    'STORE_DEREF': -1,
    'STORE_FAST': -1,
    'STORE_FAST_LOAD_FAST': 0,
    'STORE_FAST_STORE_FAST': -2,
    'STORE_GLOBAL': -1,
    'STORE_NAME': -1,
    'STORE_SLICE': -4,
    'STORE_SUBSCR': -3,
    'SWAP': 0,
    'TO_BOOL': 0,
    'UNARY_INVERT': 0,
    'UNARY_NEGATIVE': 0,
    'UNARY_NOT': 0,
    'WITH_EXCEPT_START': 1,
    'YIELD_VALUE': 0,
}

# Opcodes whose net effect genuinely depends on the oparg.
_stack_effects_oparg = {
    'BUILD_CONST_KEY_MAP': lambda oparg: -oparg,
    'BUILD_LIST': lambda oparg: 1 - oparg,
    'BUILD_MAP': lambda oparg: 1 - oparg * 2,
    'BUILD_SET': lambda oparg: 1 - oparg,
    'BUILD_SLICE': lambda oparg: -2 if oparg == 3 else -1,
    'BUILD_STRING': lambda oparg: 1 - oparg,
    'BUILD_TUPLE': lambda oparg: 1 - oparg,
    'CALL': lambda oparg: -1 - oparg,
    'CALL_FUNCTION_EX': lambda oparg: -2 - (oparg & 1),
    'CALL_KW': lambda oparg: -2 - oparg,
    'INSTRUMENTED_LOAD_SUPER_ATTR': lambda oparg: (oparg & 1) - 2,
    'LOAD_ATTR': lambda oparg: oparg & 1,
    'LOAD_GLOBAL': lambda oparg: 1 + (oparg & 1),
    'LOAD_SUPER_ATTR': lambda oparg: (oparg & 1) - 2,
    'RAISE_VARARGS': lambda oparg: -oparg,
    'UNPACK_EX': lambda oparg: (oparg >> 8) + (oparg & 0xFF),
    'UNPACK_SEQUENCE': lambda oparg: oparg - 1,
}

_stack_effects = {opmap[_n]: _e for _n, _e in _stack_effects.items()}
_stack_effects_oparg = {opmap[_n]: _e for _n, _e in _stack_effects_oparg.items()}


def stack_effect(opcode, oparg=None, *, jump=None):
    """Net stack effect of `opcode` with argument `oparg`.

    Mirrors CPython 3.13's `_opcode.stack_effect`: oparg defaults to 0,
    jump does not change the effect of any real (non-pseudo) opcode."""
    if jump not in (None, True, False):
        raise ValueError("stack_effect: jump must be False, True or None")
    effect = _stack_effects.get(opcode)
    if effect is not None:
        return effect
    formula = _stack_effects_oparg.get(opcode)
    if formula is None:
        raise ValueError("invalid opcode or oparg")
    return formula(0 if oparg is None else oparg)
