// Generated by tools/gen_ucd_tables.py from CPython 3.13
// (UCD 15.1.0). Do not edit.

pub const SHIFT: u32 = 7;
pub const N_RECORDS: usize = 16659;
pub const CATEGORIES: &[&str] = &["Cc", "Zs", "Po", "Sc", "Ps", "Pe", "Sm", "Pd", "Nd", "Lu", "Sk", "Pc", "Ll", "So", "Lo", "Pi", "Cf", "No", "Pf", "Lt", "Lm", "Mn", "Cn", "Me", "Mc", "Nl", "Zl", "Zp", "Cs", "Co"];
pub const BIDIRECTIONALS: &[&str] = &["BN", "S", "B", "WS", "ON", "ET", "ES", "CS", "EN", "L", "NSM", "", "R", "AN", "AL", "LRE", "RLE", "PDF", "LRO", "RLO", "LRI", "RLI", "FSI", "PDI"];
pub const EASTASIANWIDTHS: &[&str] = &["N", "Na", "A", "W", "H", "F"];
pub const DECOMP_PREFIXES: &[&str] = &["", "<noBreak>", "<compat>", "<super>", "<sub>", "<vertical>", "<wide>", "<narrow>", "<small>", "<square>", "<fraction>", "<font>", "<circle>", "<initial>", "<medial>", "<final>", "<isolated>"];
/// Hex-suffixed algorithmic name ranges (prefix, first cp, last cp).
pub const ALGO_RANGES: &[(&str, u32, u32)] = &[
    ("CJK UNIFIED IDEOGRAPH-", 0x3400, 0x4DBF),
    ("CJK UNIFIED IDEOGRAPH-", 0x4E00, 0x9FFF),
    ("CJK COMPATIBILITY IDEOGRAPH-", 0xF900, 0xFA6D),
    ("CJK COMPATIBILITY IDEOGRAPH-", 0xFA70, 0xFAD9),
    ("KHITAN SMALL SCRIPT CHARACTER-", 0x18B00, 0x18CD5),
    ("NUSHU CHARACTER-", 0x1B170, 0x1B2FB),
    ("CJK UNIFIED IDEOGRAPH-", 0x20000, 0x2A6DF),
    ("CJK UNIFIED IDEOGRAPH-", 0x2A700, 0x2B739),
    ("CJK UNIFIED IDEOGRAPH-", 0x2B740, 0x2B81D),
    ("CJK UNIFIED IDEOGRAPH-", 0x2B820, 0x2CEA1),
    ("CJK UNIFIED IDEOGRAPH-", 0x2CEB0, 0x2EBE0),
    ("CJK UNIFIED IDEOGRAPH-", 0x2EBF0, 0x2EE5D),
    ("CJK COMPATIBILITY IDEOGRAPH-", 0x2F800, 0x2FA1D),
    ("CJK UNIFIED IDEOGRAPH-", 0x30000, 0x3134A),
    ("CJK UNIFIED IDEOGRAPH-", 0x31350, 0x323AF),
];
/// HANGUL SYLLABLE ranges (first cp, last cp).
pub const HANGUL_RANGES: &[(u32, u32)] = &[
    (0xAC00, 0xD7A3),
];
/// Hex-suffixed ranges `lookup()`/`\N` accept but `name()` does not generate.
pub const LOOKUP_ONLY_RANGES: &[(&str, u32, u32)] = &[
    ("TANGUT IDEOGRAPH-", 0x17000, 0x187F7),
    ("TANGUT IDEOGRAPH-", 0x18D00, 0x18D08),
];
// Ctype/case flag bits (case_records.bin u16).
pub const FLAG_ALPHA: u16 = 0x0001;
pub const FLAG_DECIMAL: u16 = 0x0002;
pub const FLAG_DIGIT: u16 = 0x0004;
pub const FLAG_NUMERIC: u16 = 0x0008;
pub const FLAG_SPACE: u16 = 0x0010;
pub const FLAG_LOWER: u16 = 0x0020;
pub const FLAG_UPPER: u16 = 0x0040;
pub const FLAG_TITLE: u16 = 0x0080;
pub const FLAG_CASED: u16 = 0x0100;
pub const FLAG_CASE_IGNORABLE: u16 = 0x0200;
pub const FLAG_ALNUM: u16 = 0x0400;
pub const FLAG_XID_START: u16 = 0x0800;
pub const FLAG_XID_CONTINUE: u16 = 0x1000;
pub const FLAG_PRINTABLE: u16 = 0x2000;
