//! Generated UCD 15.1.0 database — RFC 0050 WS4.
//!
//! Backing store for the `unicodedata` module: packed tables generated by
//! `tools/gen_ucd_tables.py` from host CPython 3.13 (whose database *is*
//! UCD 15.1.0), so every property answer — including the `ucd_3_2_0`
//! snapshot — is bit-identical to CPython's `Modules/unicodedata_db.h`.
//!
//! Layout notes live in the generator; in short: a two-level `splitbins`
//! index (`index1`/`index2`) maps a code point to one of ~16K unique
//! 12-byte property records, names are a sorted `(cp, len, bytes)` stream
//! plus algorithmic ranges (Hangul syllables + hex-suffixed ideographs),
//! and canonical composition pairs are probed with exclusions already
//! applied.

use std::collections::HashMap;
use std::sync::OnceLock;

// The generator emits every table `pub` with no knowledge of what this
// engine consumes (e.g. `HANGUL_RANGES` is folded into hardcoded Hangul
// arithmetic), hence the dead-code/unreachable-pub allowances.
#[allow(clippy::all, dead_code, unreachable_pub)]
mod meta {
    include!("meta.rs");
}

pub use meta::{BIDIRECTIONALS, CATEGORIES, DECOMP_PREFIXES, EASTASIANWIDTHS};

static RECORDS: &[u8] = include_bytes!("records.bin");
static INDEX1: &[u8] = include_bytes!("index1.bin");
static INDEX2: &[u8] = include_bytes!("index2.bin");
static INDEX1_32: &[u8] = include_bytes!("index1_32.bin");
static INDEX2_32: &[u8] = include_bytes!("index2_32.bin");
static NUMERIC: &[u8] = include_bytes!("numeric.bin");
static DECOMP: &[u8] = include_bytes!("decomp.bin");
static NAMES: &[u8] = include_bytes!("names.bin");
static NAMES32: &[u8] = include_bytes!("names32.bin");
static COMP: &[u8] = include_bytes!("comp.bin");

const RECORD_SIZE: usize = 12;
const SHIFT: u32 = meta::SHIFT;

fn u16le(b: &[u8], off: usize) -> u16 {
    u16::from_le_bytes([b[off], b[off + 1]])
}

fn u24le(b: &[u8], off: usize) -> u32 {
    u32::from(b[off]) | (u32::from(b[off + 1]) << 8) | (u32::from(b[off + 2]) << 16)
}

/// A resolved per-code-point property record.
#[derive(Clone, Copy, Debug)]
pub struct Record {
    rec: &'static [u8],
}

fn record_bytes(cp: u32, index1: &'static [u8], index2: &'static [u8]) -> &'static [u8] {
    debug_assert!(cp < 0x0011_0000);
    let block = u16le(index1, ((cp >> SHIFT) as usize) * 2) as usize;
    let idx = (block << SHIFT) | (cp as usize & ((1 << SHIFT) - 1));
    let rid = u16le(index2, idx * 2) as usize;
    &RECORDS[rid * RECORD_SIZE..(rid + 1) * RECORD_SIZE]
}

/// Property record for `cp`; `old` selects the UCD 3.2.0 snapshot.
pub fn record(cp: u32, old: bool) -> Record {
    let rec = if old {
        record_bytes(cp, INDEX1_32, INDEX2_32)
    } else {
        record_bytes(cp, INDEX1, INDEX2)
    };
    Record { rec }
}

impl Record {
    pub fn category(self) -> &'static str {
        CATEGORIES[self.rec[0] as usize]
    }

    pub fn bidirectional(self) -> &'static str {
        BIDIRECTIONALS[self.rec[1] as usize]
    }

    pub fn combining(self) -> u8 {
        self.rec[2]
    }

    pub fn mirrored(self) -> bool {
        self.rec[3] != 0
    }

    pub fn east_asian_width(self) -> &'static str {
        EASTASIANWIDTHS[self.rec[4] as usize]
    }

    pub fn decimal(self) -> Option<u8> {
        match self.rec[5] {
            0xFF => None,
            d => Some(d),
        }
    }

    pub fn digit(self) -> Option<u8> {
        match self.rec[6] {
            0xFF => None,
            d => Some(d),
        }
    }

    pub fn numeric(self) -> Option<f64> {
        match u16le(self.rec, 7) {
            0xFFFF => None,
            i => {
                let off = (i as usize) * 8;
                Some(f64::from_le_bytes(
                    NUMERIC[off..off + 8].try_into().expect("8-byte f64"),
                ))
            }
        }
    }

    /// Raw decomposition: `(tag prefix, mapped code points)`, or `None`.
    pub fn decomposition(self) -> Option<(&'static str, DecompCps)> {
        match u24le(self.rec, 9) {
            0xFF_FFFF => None,
            off => {
                let off = off as usize;
                let prefix = DECOMP_PREFIXES[DECOMP[off] as usize];
                let len = DECOMP[off + 1] as usize;
                Some((
                    prefix,
                    DecompCps {
                        off: off + 2,
                        len,
                        i: 0,
                    },
                ))
            }
        }
    }

    /// CPython's `unicodedata.decomposition()` text form, e.g.
    /// `"<compat> 0020 0301"` — empty string when there is none.
    pub fn decomposition_string(self) -> String {
        let Some((prefix, cps)) = self.decomposition() else {
            return String::new();
        };
        let mut out = String::new();
        if !prefix.is_empty() {
            out.push_str(prefix);
        }
        for cp in cps {
            if !out.is_empty() {
                out.push(' ');
            }
            out.push_str(&format!("{cp:04X}"));
        }
        out
    }
}

/// Iterator over a record's decomposition code points.
#[derive(Clone, Debug)]
pub struct DecompCps {
    off: usize,
    len: usize,
    i: usize,
}

impl Iterator for DecompCps {
    type Item = u32;

    fn next(&mut self) -> Option<u32> {
        if self.i >= self.len {
            return None;
        }
        let cp = u24le(DECOMP, self.off + self.i * 3);
        self.i += 1;
        Some(cp)
    }
}

/// Whether `cp` was assigned (had a name) in UCD 3.2.0.
pub fn assigned_in_32(cp: u32) -> bool {
    NAMES32[(cp >> 3) as usize] & (1 << (cp & 7)) != 0
}

// ---------------------------------------------------------------------------
// names
// ---------------------------------------------------------------------------

// Hangul syllable name components (Jamo.txt short names).
const HANGUL_L: [&str; 19] = [
    "G", "GG", "N", "D", "DD", "R", "M", "B", "BB", "S", "SS", "", "J", "JJ", "C", "K", "T", "P",
    "H",
];
const HANGUL_V: [&str; 21] = [
    "A", "AE", "YA", "YAE", "EO", "E", "YEO", "YE", "O", "WA", "WAE", "OE", "YO", "U", "WEO", "WE",
    "WI", "YU", "EU", "YI", "I",
];
const HANGUL_T: [&str; 28] = [
    "", "G", "GG", "GS", "N", "NJ", "NH", "D", "L", "LG", "LM", "LB", "LS", "LT", "LP", "LH", "M",
    "B", "BS", "S", "SS", "NG", "J", "C", "K", "T", "P", "H",
];

const S_BASE: u32 = 0xAC00;
const L_BASE: u32 = 0x1100;
const V_BASE: u32 = 0x1161;
const T_BASE: u32 = 0x11A7;
const V_COUNT: u32 = 21;
const T_COUNT: u32 = 28;
const S_COUNT: u32 = 19 * V_COUNT * T_COUNT;

fn hangul_name(cp: u32) -> Option<String> {
    if !(S_BASE..S_BASE + S_COUNT).contains(&cp) {
        return None;
    }
    let s = cp - S_BASE;
    let l = (s / (V_COUNT * T_COUNT)) as usize;
    let v = ((s % (V_COUNT * T_COUNT)) / T_COUNT) as usize;
    let t = (s % T_COUNT) as usize;
    Some(format!(
        "HANGUL SYLLABLE {}{}{}",
        HANGUL_L[l], HANGUL_V[v], HANGUL_T[t]
    ))
}

fn hangul_lookup(rest: &str) -> Option<u32> {
    // Greedy longest-match on L, then V, then T (CPython _cpname parse).
    let (l, rest) = longest_prefix(rest, &HANGUL_L)?;
    let (v, rest) = longest_prefix(rest, &HANGUL_V)?;
    let (t, rest) = longest_prefix(rest, &HANGUL_T)?;
    if !rest.is_empty() {
        return None;
    }
    Some(S_BASE + ((l as u32) * V_COUNT + v as u32) * T_COUNT + t as u32)
}

fn longest_prefix<'a>(s: &'a str, table: &[&str]) -> Option<(usize, &'a str)> {
    let mut best: Option<(usize, &'a str)> = None;
    for (i, cand) in table.iter().enumerate() {
        if let Some(rest) = s.strip_prefix(cand) {
            match best {
                Some((bi, _)) if table[bi].len() >= cand.len() => {}
                _ => best = Some((i, rest)),
            }
        }
    }
    best
}

struct NameIndex {
    /// Sorted `(cp, byte-range in NAMES)` for the stored (non-algorithmic)
    /// names.
    by_cp: Vec<(u32, u32, u8)>, // (cp, offset of name bytes, len)
    /// Normalized name -> cp (spaces/hyphens squeezed per CPython's loose
    /// matching is NOT applied — CPython lookup is exact-with-aliases; we
    /// index the exact uppercase names).
    by_name: HashMap<&'static str, u32>,
}

fn name_index() -> &'static NameIndex {
    static IDX: OnceLock<NameIndex> = OnceLock::new();
    IDX.get_or_init(|| {
        let mut by_cp = Vec::with_capacity(40_000);
        let mut by_name = HashMap::with_capacity(40_000);
        let mut off = 0usize;
        while off < NAMES.len() {
            let cp = u24le(NAMES, off);
            let len = NAMES[off + 3] as usize;
            let start = off + 4;
            let name = std::str::from_utf8(&NAMES[start..start + len]).expect("ascii name");
            by_cp.push((cp, start as u32, len as u8));
            by_name.insert(name, cp);
            off = start + len;
        }
        NameIndex { by_cp, by_name }
    })
}

/// UCD name for `cp` (algorithmic ranges included); `None` when unassigned
/// or nameless (controls).
pub fn name(cp: u32) -> Option<String> {
    if let Some(n) = hangul_name(cp) {
        return Some(n);
    }
    for &(prefix, lo, hi) in meta::ALGO_RANGES {
        if (lo..=hi).contains(&cp) {
            return Some(format!("{prefix}{cp:04X}"));
        }
    }
    let idx = name_index();
    match idx.by_cp.binary_search_by_key(&cp, |&(c, _, _)| c) {
        Ok(i) => {
            let (_, start, len) = idx.by_cp[i];
            Some(
                std::str::from_utf8(&NAMES[start as usize..start as usize + len as usize])
                    .expect("ascii name")
                    .to_owned(),
            )
        }
        Err(_) => None,
    }
}

/// Reverse lookup: exact (case-insensitive) UCD name -> code point,
/// canonical names only (stored + algorithmic, including the lookup-only
/// Tangut ranges). NameAliases entries live in [`lookup_with_aliases`] —
/// the `ucd_3_2_0` snapshot must reject them.
pub fn lookup(name_arg: &str) -> Option<u32> {
    let upper = name_arg.to_ascii_uppercase();
    if let Some(rest) = upper.strip_prefix("HANGUL SYLLABLE ") {
        return hangul_lookup(rest);
    }
    for &(prefix, lo, hi) in meta::ALGO_RANGES.iter().chain(meta::LOOKUP_ONLY_RANGES) {
        if let Some(hex) = upper.strip_prefix(prefix) {
            if let Ok(cp) = u32::from_str_radix(hex, 16) {
                // The name must round-trip exactly (no leading zeros beyond
                // the canonical %04X form) and land in the range.
                if format!("{cp:04X}") == hex && (lo..=hi).contains(&cp) {
                    return Some(cp);
                }
            }
        }
    }
    name_index().by_name.get(upper.as_str()).copied()
}

/// [`lookup`] plus NameAliases.txt entries — what CPython's `getcode`
/// resolves for the *current* database (`unicodedata.lookup`, `\N{...}`).
pub fn lookup_with_aliases(name_arg: &str) -> Option<u32> {
    lookup(name_arg).or_else(|| {
        alias_index()
            .get(name_arg.to_ascii_uppercase().as_str())
            .copied()
    })
}

static ALIASES: &[u8] = include_bytes!("aliases.bin");
static SEQS: &[u8] = include_bytes!("seqs.bin");

fn alias_index() -> &'static HashMap<&'static str, u32> {
    static IDX: OnceLock<HashMap<&'static str, u32>> = OnceLock::new();
    IDX.get_or_init(|| {
        let mut m = HashMap::with_capacity(512);
        let mut off = 0usize;
        while off < ALIASES.len() {
            let cp = u24le(ALIASES, off);
            let len = ALIASES[off + 3] as usize;
            let name = std::str::from_utf8(&ALIASES[off + 4..off + 4 + len]).expect("ascii alias");
            m.insert(name, cp);
            off += 4 + len;
        }
        m
    })
}

fn seq_index() -> &'static HashMap<&'static str, Vec<u32>> {
    static IDX: OnceLock<HashMap<&'static str, Vec<u32>>> = OnceLock::new();
    IDX.get_or_init(|| {
        let mut m = HashMap::with_capacity(512);
        let mut off = 0usize;
        while off < SEQS.len() {
            let n = SEQS[off] as usize;
            let cps: Vec<u32> = (0..n).map(|i| u24le(SEQS, off + 1 + i * 3)).collect();
            off += 1 + n * 3;
            let len = SEQS[off] as usize;
            let name =
                std::str::from_utf8(&SEQS[off + 1..off + 1 + len]).expect("ascii sequence name");
            m.insert(name, cps);
            off += 1 + len;
        }
        m
    })
}

/// NamedSequences.txt lookup (`unicodedata.lookup` only — `\N{...}` and
/// the `ucd_3_2_0` snapshot both reject named sequences).
pub fn lookup_named_sequence(name_arg: &str) -> Option<&'static [u32]> {
    seq_index()
        .get(name_arg.to_ascii_uppercase().as_str())
        .map(Vec::as_slice)
}

// ---------------------------------------------------------------------------
// normalization
// ---------------------------------------------------------------------------

fn comp_index() -> &'static HashMap<(u32, u32), u32> {
    static IDX: OnceLock<HashMap<(u32, u32), u32>> = OnceLock::new();
    IDX.get_or_init(|| {
        let mut m = HashMap::with_capacity(COMP.len() / 9);
        let mut off = 0;
        while off < COMP.len() {
            let a = u24le(COMP, off);
            let b = u24le(COMP, off + 3);
            let c = u24le(COMP, off + 6);
            m.insert((a, b), c);
            off += 9;
        }
        m
    })
}

fn hangul_decompose(cp: u32, out: &mut Vec<u32>) -> bool {
    if !(S_BASE..S_BASE + S_COUNT).contains(&cp) {
        return false;
    }
    let s = cp - S_BASE;
    out.push(L_BASE + s / (V_COUNT * T_COUNT));
    out.push(V_BASE + (s % (V_COUNT * T_COUNT)) / T_COUNT);
    let t = s % T_COUNT;
    if t != 0 {
        out.push(T_BASE + t);
    }
    true
}

/// `unicodedata.c` `normalization_3_2_0`: NormalizationCorrections.txt —
/// decompositions that were *corrected* after 3.2.0, so the snapshot's
/// normalizer must use the old target (the property record keeps the
/// current text; only normalization consults this).
const NORM_CORRECTIONS_32: &[(u32, u32)] = &[
    (0xF951, 0x964B),
    (0x2F868, 0x2136A),
    (0x2F874, 0x5F33),
    (0x2F91F, 0x43AB),
    (0x2F95F, 0x7AAE),
    (0x2F9BF, 0x4D57),
];

fn decompose_cp(cp: u32, compat: bool, old: bool, out: &mut Vec<u32>) {
    if old {
        if let Ok(i) = NORM_CORRECTIONS_32.binary_search_by_key(&cp, |&(c, _)| c) {
            decompose_cp(NORM_CORRECTIONS_32[i].1, compat, old, out);
            return;
        }
    }
    if hangul_decompose(cp, out) {
        return;
    }
    // Lone surrogates and unassigned code points are ccc=0 starters with no
    // decomposition: they pass through.
    if cp < 0x0011_0000 {
        if let Some((prefix, cps)) = record(cp, old).decomposition() {
            if prefix.is_empty() || compat {
                for c in cps {
                    decompose_cp(c, compat, old, out);
                }
                return;
            }
        }
    }
    out.push(cp);
}

fn combining_of(cp: u32, old: bool) -> u8 {
    if cp < 0x0011_0000 {
        record(cp, old).combining()
    } else {
        0
    }
}

/// Canonical-order a decomposed sequence (stable exchange on adjacent
/// out-of-order combining classes).
fn canonical_order(cps: &mut [u32], old: bool) {
    let mut i = 1;
    while i < cps.len() {
        let cc = combining_of(cps[i], old);
        if cc != 0 && combining_of(cps[i - 1], old) > cc {
            cps.swap(i - 1, i);
            if i > 1 {
                i -= 1;
                continue;
            }
        }
        i += 1;
    }
}

fn hangul_compose(a: u32, b: u32) -> Option<u32> {
    // L + V
    if (L_BASE..L_BASE + 19).contains(&a) && (V_BASE..V_BASE + V_COUNT).contains(&b) {
        return Some(S_BASE + ((a - L_BASE) * V_COUNT + (b - V_BASE)) * T_COUNT);
    }
    // LV + T
    if (S_BASE..S_BASE + S_COUNT).contains(&a)
        && (a - S_BASE).is_multiple_of(T_COUNT)
        && (T_BASE + 1..T_BASE + T_COUNT).contains(&b)
    {
        return Some(a + (b - T_BASE));
    }
    None
}

fn compose(cps: &mut Vec<u32>, old: bool) {
    if cps.is_empty() {
        return;
    }
    let pairs = comp_index();
    let mut out: Vec<u32> = Vec::with_capacity(cps.len());
    let mut i = 0;
    while i < cps.len() {
        let starter = cps[i];
        if combining_of(starter, old) != 0 {
            out.push(starter);
            i += 1;
            continue;
        }
        // Compose the run following this starter.
        let mut composed = starter;
        let mut pending: Vec<u32> = Vec::new();
        let mut last_cc: i32 = -1;
        let mut j = i + 1;
        while j < cps.len() {
            let c = cps[j];
            let cc = i32::from(combining_of(c, old));
            if cc == 0 {
                // Next starter: try starter-pair composition (only when no
                // combining marks are pending after the current composite).
                if pending.is_empty() && last_cc == -1 {
                    if let Some(newc) =
                        hangul_compose(composed, c).or_else(|| pairs.get(&(composed, c)).copied())
                    {
                        composed = newc;
                        j += 1;
                        continue;
                    }
                }
                break;
            }
            if cc > last_cc {
                if let Some(newc) =
                    hangul_compose(composed, c).or_else(|| pairs.get(&(composed, c)).copied())
                {
                    composed = newc;
                    j += 1;
                    continue;
                }
            }
            pending.push(c);
            last_cc = cc;
            j += 1;
        }
        out.push(composed);
        out.extend_from_slice(&pending);
        i = j;
    }
    *cps = out;
}

/// Normalize a code-point sequence. `form` must be one of
/// NFC/NFD/NFKC/NFKD (validated by the caller).
pub fn normalize(form: &str, cps: &[u32], old: bool) -> Vec<u32> {
    let (compat, compose_after) = match form {
        "NFC" => (false, true),
        "NFD" => (false, false),
        "NFKC" => (true, true),
        "NFKD" => (true, false),
        _ => unreachable!("caller validates the form"),
    };
    let mut out = Vec::with_capacity(cps.len() + 8);
    for &cp in cps {
        decompose_cp(cp, compat, old, &mut out);
    }
    canonical_order(&mut out, old);
    if compose_after {
        compose(&mut out, old);
    }
    out
}

// ---------------------------------------------------------------------------
// ctype flags + full case mappings (CPython's unicodectype.c equivalent)
// ---------------------------------------------------------------------------

static CASE_RECORDS: &[u8] = include_bytes!("case_records.bin");
static CASE_INDEX1: &[u8] = include_bytes!("case_index1.bin");
static CASE_INDEX2: &[u8] = include_bytes!("case_index2.bin");
static CASE_POOL: &[u8] = include_bytes!("case_pool.bin");

/// 14 bytes: u16 flags, then u24 lower/upper/title/casefold refs.
const CASE_RECORD_SIZE: usize = 14;
/// Ref sentinel: the mapping is the identity.
const CASE_IDENTITY: u32 = 0xFF_FFFF;

pub use meta::{
    FLAG_ALNUM, FLAG_ALPHA, FLAG_CASED, FLAG_CASE_IGNORABLE, FLAG_DECIMAL, FLAG_DIGIT, FLAG_LOWER,
    FLAG_NUMERIC, FLAG_PRINTABLE, FLAG_SPACE, FLAG_TITLE, FLAG_UPPER, FLAG_XID_CONTINUE,
    FLAG_XID_START,
};

fn case_record(cp: u32) -> &'static [u8] {
    debug_assert!(cp < 0x0011_0000);
    let block = u16le(CASE_INDEX1, ((cp >> SHIFT) as usize) * 2) as usize;
    let idx = (block << SHIFT) | (cp as usize & ((1 << SHIFT) - 1));
    let rid = u16le(CASE_INDEX2, idx * 2) as usize;
    &CASE_RECORDS[rid * CASE_RECORD_SIZE..(rid + 1) * CASE_RECORD_SIZE]
}

/// CPython-parity ctype predicate flags for `cp` (`FLAG_*`).
pub fn case_flags(cp: u32) -> u16 {
    u16le(case_record(cp), 0)
}

/// `_PyUnicode_IsCased` (DerivedCoreProperties `Cased`).
pub fn is_cased(cp: u32) -> bool {
    case_flags(cp) & FLAG_CASED != 0
}

/// `_PyUnicode_IsCaseIgnorable` (DerivedCoreProperties `Case_Ignorable`).
pub fn is_case_ignorable(cp: u32) -> bool {
    case_flags(cp) & FLAG_CASE_IGNORABLE != 0
}

/// A full case mapping: 1..=3 code points (SpecialCasing expansions such
/// as `ß` -> "SS" included).
#[derive(Clone, Copy, Debug)]
pub struct CaseMap {
    buf: [u32; 3],
    len: u8,
}

impl CaseMap {
    pub fn single(cp: u32) -> Self {
        Self {
            buf: [cp, 0, 0],
            len: 1,
        }
    }

    pub fn as_slice(&self) -> &[u32] {
        &self.buf[..self.len as usize]
    }
}

fn case_map(cp: u32, field: usize) -> CaseMap {
    let r = u24le(case_record(cp), 2 + field * 3);
    if r == CASE_IDENTITY {
        return CaseMap::single(cp);
    }
    if r < 0x0011_0000 {
        return CaseMap::single(r);
    }
    let off = (r - 0x0011_0000) as usize;
    let len = CASE_POOL[off] as usize;
    debug_assert!((2..=3).contains(&len));
    let mut buf = [0u32; 3];
    for (i, slot) in buf.iter_mut().take(len).enumerate() {
        *slot = u24le(CASE_POOL, off + 1 + i * 3);
    }
    CaseMap {
        buf,
        len: len as u8,
    }
}

/// `_PyUnicode_ToLowercaseFull` (context-free; `str.lower()` adds the
/// Final_Sigma rule on top of this).
pub fn to_lower_full(cp: u32) -> CaseMap {
    case_map(cp, 0)
}

/// `_PyUnicode_ToUppercaseFull`.
pub fn to_upper_full(cp: u32) -> CaseMap {
    case_map(cp, 1)
}

/// `_PyUnicode_ToTitleFull`.
pub fn to_title_full(cp: u32) -> CaseMap {
    case_map(cp, 2)
}

/// `_PyUnicode_ToFoldedFull` (`str.casefold()`, no sigma context).
pub fn to_fold_full(cp: u32) -> CaseMap {
    case_map(cp, 3)
}
